# Generated by Django 3.1.6 on 2021-02-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Techie',
            fields=[
                ('techie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('techie_name', models.CharField(max_length=200)),
                ('techie_skill', models.CharField(max_length=20)),
                ('techie_profile', models.CharField(max_length=50)),
                ('techie_salary', models.IntegerField()),
            ],
        ),
    ]
